### ISSUE TITLE
Can't download the .tgz file

### ISSUE THREAD

**Issue by ruoyuxie** [danielvarga/hunalign#8]
Closing the issue. It was my connection problem. Thanks! 
----------------------

Hi,

I was not able to connect to the server as a guest and download the source code file or the package. 

Here are the steps I took:
1. Click ftp://ftp.mokk.bme.hu/Hunglish/src/hunalign/latest/hunalign-1.1.tgz
2. Connect to the server as a Guest on the pop-out window
3. Wait and nothing happens 

Please help. Thanks!

**Comment by ruoyuxie** [comment]
close the issue. It was my connection problem. Thanks!

**Comment by soundmemories** [comment]
> close the issue. It was my connection problem. Thanks!
Hi, I also meet the same problem, can you download hunalign-1.2.tgz? 
This is the official website: http://mokk.bme.hu/resources/hunalign/
This is the download link: ftp://ftp.mokk.bme.hu/Hunglish/src/hunalign/latest/hunalign-1.2.tgz
